package com.f1report.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * ReportResponseDTO – the response body for POST /api/generate-report.
 *
 * Contains the AI-generated report text plus metadata so the frontend
 * can display: the report content, when it was generated, which AI
 * model wrote it, and whether it was a fresh generation or a cached hit.
 *
 * Real-world analogy: like a doctor's report handed to a patient.
 * It contains the diagnosis (reportContent), the doctor's name (modelUsed),
 * the date written (generatedAt), and whether it's a new report or a copy
 * from the files (fromCache).
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ReportResponseDTO {

    /** DB primary key – used by the frontend to call GET /api/export-pdf/{id} */
    private Long   id;

    private Integer season;
    private Integer round;
    private String  raceName;

    /** The full journalist-style AI report text (markdown-formatted) */
    private String  reportContent;

    /** Which Groq model generated this: "llama-3.3-70b-versatile" etc. */
    private String  modelUsed;

    /** Tokens consumed in the prompt (for transparency/debugging) */
    private Integer promptTokens;

    /** Tokens consumed in the completion (AI output length) */
    private Integer completionTokens;

    /** Timestamp when the report was created */
    private LocalDateTime generatedAt;

    /**
     * true  = returned from DB (no Groq API call made, instant response)
     * false = freshly generated by Groq AI (took 5–20 seconds)
     */
    private boolean fromCache;

    // ── Denormalised race summary for display alongside the report ────────────
    private String winnerName;
    private String winnerConstructor;
}
